# Generated by Django 5.2.15 on 2026-06-19 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indikator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('diubah_pada', models.DateTimeField(auto_now=True, verbose_name='Diubah pada')),
                ('nama', models.CharField(max_length=200, unique=True)),
                ('satuan', models.CharField(blank=True, help_text='mis. km2, jiwa, %, rupiah', max_length=40)),
                ('tipe_nilai', models.CharField(choices=[('numerik', 'Numerik'), ('teks', 'Teks')], default='numerik', max_length=10)),
            ],
            options={
                'verbose_name': 'Indikator',
                'verbose_name_plural': 'Indikator',
                'ordering': ['nama'],
                'indexes': [models.Index(fields=['nama'], name='referensi_i_nama_89a90d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rincian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('diubah_pada', models.DateTimeField(auto_now=True, verbose_name='Diubah pada')),
                ('nama', models.CharField(max_length=255)),
                ('kelompok', models.CharField(blank=True, help_text='mis. Partai Politik, Jabatan, Lapangan Usaha, Kelompok Komoditas', max_length=80)),
            ],
            options={
                'verbose_name': 'Rincian',
                'verbose_name_plural': 'Rincian',
                'ordering': ['kelompok', 'nama'],
                'indexes': [models.Index(fields=['kelompok'], name='referensi_r_kelompo_251b08_idx'), models.Index(fields=['nama'], name='referensi_r_nama_7db2de_idx')],
                'constraints': [models.UniqueConstraint(fields=('nama', 'kelompok'), name='uq_rincian_nama_kelompok')],
            },
        ),
        migrations.CreateModel(
            name='Wilayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('diubah_pada', models.DateTimeField(auto_now=True, verbose_name='Diubah pada')),
                ('nama', models.CharField(max_length=120)),
                ('jenis', models.CharField(choices=[('kecamatan', 'Kecamatan'), ('kabupaten', 'Kabupaten/Kota'), ('provinsi', 'Provinsi')], default='kecamatan', max_length=20)),
                ('kode_bps', models.CharField(blank=True, max_length=20, verbose_name='Kode BPS')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anak', to='referensi.wilayah', verbose_name='Induk wilayah')),
            ],
            options={
                'verbose_name': 'Wilayah',
                'verbose_name_plural': 'Wilayah',
                'ordering': ['jenis', 'nama'],
                'indexes': [models.Index(fields=['nama'], name='referensi_w_nama_929a2e_idx'), models.Index(fields=['jenis'], name='referensi_w_jenis_40dc35_idx')],
                'constraints': [models.UniqueConstraint(fields=('nama', 'jenis', 'parent'), name='uq_wilayah_nama_jenis_parent')],
            },
        ),
    ]
