# Generated by Django 5.2.15 on 2026-06-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referensi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indikator',
            name='nama',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='rincian',
            name='nama',
            field=models.TextField(),
        ),
    ]
