# Generated by Django 5.2.15 on 2026-07-11 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referensi', '0002_alter_indikator_nama_alter_rincian_nama'),
    ]

    operations = [
        migrations.CreateModel(
            name='RincianAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('diubah_pada', models.DateTimeField(auto_now=True, verbose_name='Diubah pada')),
                ('alias_text', models.TextField(help_text='Nama rincian mentah yang akan dipetakan')),
                ('normalized_alias', models.TextField(help_text='alias_text yang dinormalisasi (lower, strip) untuk lookup cepat')),
                ('table_title_pattern', models.CharField(blank=True, help_text='Konteks judul tabel. Kosong = berlaku semua tabel.', max_length=500)),
                ('is_approved', models.BooleanField(default=True)),
                ('canonical_rincian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases_canonical', to='referensi.rincian')),
                ('raw_rincian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alias_sources', to='referensi.rincian')),
            ],
            options={
                'verbose_name': 'Rincian Alias',
                'verbose_name_plural': 'Rincian Aliases',
                'ordering': ['normalized_alias'],
                'indexes': [models.Index(fields=['normalized_alias'], name='referensi_r_normali_f2ae95_idx')],
                'constraints': [models.UniqueConstraint(fields=('normalized_alias', 'table_title_pattern'), name='uq_rincian_alias_context')],
            },
        ),
    ]
