# Generated by Django 5.2.15 on 2026-06-19 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referensi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('diubah_pada', models.DateTimeField(auto_now=True, verbose_name='Diubah pada')),
                ('judul', models.CharField(max_length=255)),
                ('tahun_terbit', models.PositiveIntegerField()),
                ('wilayah_cakupan', models.CharField(default='Kabupaten Tasikmalaya', max_length=120)),
                ('jenis', models.CharField(choices=[('digital', 'PDF Digital'), ('scan', 'Hasil Scan')], default='digital', max_length=10)),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='publikasi/')),
                ('catatan', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Publikasi',
                'verbose_name_plural': 'Publikasi',
                'ordering': ['-tahun_terbit', 'judul'],
                'constraints': [models.UniqueConstraint(fields=('judul', 'tahun_terbit'), name='uq_publikasi_judul_tahun')],
            },
        ),
        migrations.CreateModel(
            name='Bab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('diubah_pada', models.DateTimeField(auto_now=True, verbose_name='Diubah pada')),
                ('nomor', models.PositiveIntegerField()),
                ('nama', models.CharField(max_length=150)),
                ('publikasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bab_set', to='katalog.publikasi')),
            ],
            options={
                'verbose_name': 'Bab',
                'verbose_name_plural': 'Bab',
                'ordering': ['publikasi', 'nomor'],
            },
        ),
        migrations.CreateModel(
            name='Tabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('diubah_pada', models.DateTimeField(auto_now=True, verbose_name='Diubah pada')),
                ('nomor_tabel', models.CharField(help_text='mis. 1.1.1', max_length=20)),
                ('judul', models.CharField(max_length=400)),
                ('judul_en', models.CharField(blank=True, max_length=400)),
                ('sumber', models.CharField(blank=True, max_length=300)),
                ('tahun_data', models.PositiveIntegerField(blank=True, null=True)),
                ('halaman_awal', models.PositiveIntegerField(blank=True, null=True)),
                ('halaman_akhir', models.PositiveIntegerField(blank=True, null=True)),
                ('tipe_baris', models.CharField(choices=[('kecamatan', 'Per Kecamatan'), ('kabupaten', 'Per Kabupaten/Kota'), ('kategori', 'Per Kategori (rincian)')], default='kecamatan', max_length=15)),
                ('status_verifikasi', models.CharField(choices=[('draft', 'Draft'), ('ekstrak', 'Hasil Ekstraksi'), ('verifikasi', 'Sudah Diverifikasi')], default='draft', max_length=15)),
                ('bab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabel_set', to='katalog.bab')),
            ],
            options={
                'verbose_name': 'Tabel',
                'verbose_name_plural': 'Tabel',
                'ordering': ['bab', 'nomor_tabel'],
            },
        ),
        migrations.CreateModel(
            name='KolomTabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('diubah_pada', models.DateTimeField(auto_now=True, verbose_name='Diubah pada')),
                ('urutan', models.PositiveIntegerField(help_text='Posisi kolom (1 = kolom angka pertama setelah label)')),
                ('satuan', models.CharField(blank=True, max_length=40)),
                ('tahun', models.PositiveIntegerField(blank=True, null=True)),
                ('tipe_nilai', models.CharField(choices=[('numerik', 'Numerik'), ('teks', 'Teks')], default='numerik', max_length=10)),
                ('indikator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kolom_set', to='referensi.indikator')),
                ('tabel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kolom_set', to='katalog.tabel')),
            ],
            options={
                'verbose_name': 'Kolom Tabel',
                'verbose_name_plural': 'Kolom Tabel',
                'ordering': ['tabel', 'urutan'],
            },
        ),
        migrations.AddConstraint(
            model_name='bab',
            constraint=models.UniqueConstraint(fields=('publikasi', 'nomor'), name='uq_bab_publikasi_nomor'),
        ),
        migrations.AddIndex(
            model_name='tabel',
            index=models.Index(fields=['nomor_tabel'], name='katalog_tab_nomor_t_66981f_idx'),
        ),
        migrations.AddConstraint(
            model_name='tabel',
            constraint=models.UniqueConstraint(fields=('bab', 'nomor_tabel'), name='uq_tabel_bab_nomor'),
        ),
        migrations.AddConstraint(
            model_name='kolomtabel',
            constraint=models.UniqueConstraint(fields=('tabel', 'urutan'), name='uq_kolom_tabel_urutan'),
        ),
    ]
