# Generated by Django 5.2.15 on 2026-06-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabel',
            name='nama_ringkas',
            field=models.CharField(blank=True, help_text="Nama mudah dibaca, mis. 'Luas Daerah & Jumlah Pulau'", max_length=120),
        ),
    ]
