# Generated by Django 5.2.15 on 2026-06-30 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_tabel_nama_ringkas'),
        ('referensi', '0002_alter_indikator_nama_alter_rincian_nama'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('diubah_pada', models.DateTimeField(auto_now=True, verbose_name='Diubah pada')),
                ('source_publikasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs_source', to='katalog.publikasi')),
                ('target_publikasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs_target', to='katalog.publikasi')),
            ],
            options={
                'verbose_name': 'Log Sinkronisasi',
                'verbose_name_plural': 'Log Sinkronisasi',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='SyncAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('diubah_pada', models.DateTimeField(auto_now=True, verbose_name='Diubah pada')),
                ('old_satuan', models.CharField(blank=True, max_length=40)),
                ('old_tahun', models.PositiveIntegerField(blank=True, null=True)),
                ('kolom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalog.kolomtabel')),
                ('new_indikator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='referensi.indikator')),
                ('old_indikator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='referensi.indikator')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='katalog.synclog')),
            ],
            options={
                'verbose_name': 'Aksi Sinkronisasi',
                'verbose_name_plural': 'Aksi Sinkronisasi',
            },
        ),
    ]
