# Generated by Django 5.2.15 on 2026-06-19 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('katalog', '0001_initial'),
        ('referensi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fakta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('diubah_pada', models.DateTimeField(auto_now=True, verbose_name='Diubah pada')),
                ('tahun', models.PositiveIntegerField(blank=True, null=True)),
                ('nilai_num', models.DecimalField(blank=True, decimal_places=4, max_digits=24, null=True)),
                ('nilai_teks', models.CharField(blank=True, help_text='Tulisan asli dari sumber (audit)', max_length=255)),
                ('flag', models.CharField(choices=[('ada', 'Ada'), ('nihil', 'Nihil (-)'), ('tidak_tersedia', 'Tidak tersedia (...)'), ('perlu_cek', 'Perlu dicek')], default='ada', max_length=15)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fakta_dibuat', to=settings.AUTH_USER_MODEL)),
                ('kolom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fakta_set', to='katalog.kolomtabel')),
                ('rincian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fakta_set', to='referensi.rincian')),
                ('tabel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fakta_set', to='katalog.tabel')),
                ('wilayah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fakta_set', to='referensi.wilayah')),
            ],
            options={
                'verbose_name': 'Fakta',
                'verbose_name_plural': 'Fakta',
                'ordering': ['tabel', 'wilayah', 'rincian', 'tahun'],
                'indexes': [models.Index(fields=['tabel', 'tahun'], name='data_fakta_tabel_i_9240fe_idx'), models.Index(fields=['wilayah', 'tahun'], name='data_fakta_wilayah_f8fd2e_idx'), models.Index(fields=['flag'], name='data_fakta_flag_1d8bd3_idx')],
            },
        ),
    ]
