# Generated by Django 5.2.15 on 2026-06-19 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('katalog', '0002_tabel_nama_ringkas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakta',
            name='kolom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fakta_set', to='katalog.kolomtabel'),
        ),
    ]
