# Generated by Django 5.2.15 on 2026-06-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_fakta_kolom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakta',
            name='nilai_teks',
            field=models.CharField(blank=True, help_text='Tulisan asli dari sumber (audit)', max_length=500),
        ),
    ]
