# Generated by Django 5.2.15 on 2026-06-24 11:27

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_fakta_nilai_teks'),
        ('katalog', '0002_tabel_nama_ringkas'),
        ('referensi', '0002_alter_indikator_nama_alter_rincian_nama'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fakta',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='fakta',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='data_fakta_search__e20c16_gin'),
        ),
    ]
