# Generated by Django 5.2.15 on 2026-07-05 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_fakta_search_vector_and_more'),
        ('katalog', '0003_synclog_syncaction'),
        ('referensi', '0002_alter_indikator_nama_alter_rincian_nama'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('diubah_pada', models.DateTimeField(auto_now=True, verbose_name='Diubah pada')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Canonical Unit',
                'verbose_name_plural': 'Canonical Units',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CanonicalIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('diubah_pada', models.DateTimeField(auto_now=True, verbose_name='Diubah pada')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('topic', models.CharField(blank=True, help_text='Contoh: Kependudukan, Pendidikan, Ekonomi', max_length=100)),
                ('preferred_direction', models.CharField(choices=[('up', 'Naik lebih baik'), ('down', 'Turun lebih baik'), ('neutral', 'Netral')], default='neutral', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('default_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_indicators', to='data.canonicalunit')),
            ],
            options={
                'verbose_name': 'Canonical Indicator',
                'verbose_name_plural': 'Canonical Indicators',
                'ordering': ['topic', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HarmonizationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('diubah_pada', models.DateTimeField(auto_now=True, verbose_name='Diubah pada')),
                ('object_type', models.CharField(choices=[('indicator', 'Indikator'), ('unit', 'Unit'), ('value', 'Value'), ('region', 'Wilayah'), ('period', 'Periode')], max_length=20)),
                ('raw_value', models.CharField(max_length=500)),
                ('suggested_value', models.CharField(blank=True, max_length=500)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('corrected', 'Corrected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('raw_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harmonization_reviews', to='referensi.indikator')),
                ('raw_table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harmonization_reviews', to='katalog.tabel')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harmonization_reviews', to=settings.AUTH_USER_MODEL)),
                ('suggested_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_suggestions', to='data.canonicalindicator')),
                ('suggested_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_suggestions', to='data.canonicalunit')),
            ],
            options={
                'verbose_name': 'Harmonization Review',
                'verbose_name_plural': 'Harmonization Reviews',
                'ordering': ['-diubah_pada'],
            },
        ),
        migrations.CreateModel(
            name='UnitAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('diubah_pada', models.DateTimeField(auto_now=True, verbose_name='Diubah pada')),
                ('alias_text', models.CharField(max_length=100)),
                ('normalized_alias', models.CharField(max_length=100)),
                ('multiplier', models.DecimalField(decimal_places=8, default=1, help_text='Kalikan nilai mentah dengan faktor ini untuk mendapat nilai canonical.', max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('canonical_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='data.canonicalunit')),
            ],
            options={
                'verbose_name': 'Unit Alias',
                'verbose_name_plural': 'Unit Aliases',
                'ordering': ['canonical_unit', 'alias_text'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('diubah_pada', models.DateTimeField(auto_now=True, verbose_name='Diubah pada')),
                ('alias_text', models.CharField(max_length=500)),
                ('normalized_alias', models.CharField(max_length=500)),
                ('table_title_pattern', models.CharField(blank=True, help_text='Konteks judul tabel. Wajib diisi untuk alias generik seperti Laki-laki/Perempuan/Jumlah.', max_length=500)),
                ('topic_hint', models.CharField(blank=True, help_text='Konteks bab/topik bila tersedia', max_length=120)),
                ('match_type', models.CharField(choices=[('exact', 'Exact'), ('contextual', 'Contextual'), ('fuzzy', 'Fuzzy'), ('manual', 'Manual'), ('imported', 'Imported')], default='manual', max_length=20)),
                ('confidence', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('is_approved', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('canonical_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='data.canonicalindicator')),
                ('raw_indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_aliases', to='referensi.indikator')),
                ('unit_alias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_aliases', to='data.unitalias')),
            ],
            options={
                'verbose_name': 'Indicator Alias',
                'verbose_name_plural': 'Indicator Aliases',
                'ordering': ['canonical_indicator', 'alias_text'],
            },
        ),
        migrations.AddIndex(
            model_name='canonicalindicator',
            index=models.Index(fields=['topic', 'is_active'], name='data_canoni_topic_4bc188_idx'),
        ),
        migrations.AddIndex(
            model_name='harmonizationreview',
            index=models.Index(fields=['object_type', 'status'], name='data_harmon_object__9069bf_idx'),
        ),
        migrations.AddIndex(
            model_name='harmonizationreview',
            index=models.Index(fields=['confidence'], name='data_harmon_confide_d5c7c8_idx'),
        ),
        migrations.AddIndex(
            model_name='unitalias',
            index=models.Index(fields=['normalized_alias'], name='data_unital_normali_e8a595_idx'),
        ),
        migrations.AddConstraint(
            model_name='unitalias',
            constraint=models.UniqueConstraint(fields=('normalized_alias',), name='uq_unit_alias_normalized'),
        ),
        migrations.AddIndex(
            model_name='indicatoralias',
            index=models.Index(fields=['normalized_alias'], name='data_indica_normali_c8068f_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatoralias',
            index=models.Index(fields=['table_title_pattern'], name='data_indica_table_t_c6c28d_idx'),
        ),
        migrations.AddIndex(
            model_name='indicatoralias',
            index=models.Index(fields=['is_approved', 'match_type'], name='data_indica_is_appr_534e3f_idx'),
        ),
        migrations.AddConstraint(
            model_name='indicatoralias',
            constraint=models.UniqueConstraint(fields=('normalized_alias', 'table_title_pattern', 'topic_hint'), name='uq_indicator_alias_context'),
        ),
    ]
