# Generated by Django 5.2.15 on 2026-07-29 17:27

import apps.manual_import.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('publication_year', models.IntegerField()),
                ('master_source_year', models.IntegerField(default=apps.manual_import.models._default_master_source_year)),
                ('mode', models.CharField(default='strict', max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('validated', 'Validated'), ('committed', 'Committed'), ('rejected', 'Rejected')], default='uploaded', max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='manual_import/uploads/%Y/%m/%d/')),
                ('validation_report', models.JSONField(blank=True, default=dict)),
                ('preview_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('publication_year', models.IntegerField()),
                ('master_source_year', models.IntegerField(default=apps.manual_import.models._default_master_source_year)),
                ('mode', models.CharField(default='strict', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('committed', 'Committed'), ('failed', 'Failed')], default='parsed', max_length=20)),
                ('raw_filename', models.CharField(max_length=255)),
                ('validation_report', models.JSONField(blank=True, default=dict)),
                ('preview_summary', models.JSONField(blank=True, default=dict)),
                ('tables_affected', models.JSONField(blank=True, default=list)),
                ('faktas_inserted', models.IntegerField(default=apps.manual_import.models._default_zero)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manual_import.importupload')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
